### ISSUE TITLE
Need info for building / running

### ISSUE THREAD

**Issue by Sciss** [oswetto/LoboEvolution#45]
Hi there!

I have tried to understand the project build structure, recreating it in sbt (I also tried importing the Eclipse build in IntelliJ, but external library dependencies are missing): https://github.com/Sciss/LoboEvolution/blob/sciss-build/build.sbt (you can use `./sbt loboevolution-demo/run` in that branch)

Now I think I'm almost there, but I don't understand what the main entry point for the browser component is. I don't want to go the route via Iz installer, I need this eventually as a library I can link to. So my hunch was that `TestEntry` in the `Testing` module would do what I want. Indeed, I can fire that up. But every time I try to load a URL (`Parse & Render`), I just get a white background and some SQL errors. Here are two examples:

```
ERROR LAFSettings org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: LOOK_AND_FEEL)
 org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: LOOK_AND_FEEL)
	at org.sqlite.core.DB.newSQLException(DB.java:941)
	at org.sqlite.core.DB.newSQLException(DB.java:953)
	at org.sqlite.core.DB.throwex(DB.java:918)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:73)
	at org.loboevolution.font.LAFSettings.retriveFontDate(LAFSettings.java:128)
	at org.loboevolution.font.LAFSettings.getIstance(LAFSettings.java:119)
	at org.loboevolution.font.FontFactory.<init>(FontFactory.java:71)
	at org.loboevolution.font.FontFactory.<clinit>(FontFactory.java:59)
	at org.loboevolution.html.renderstate.StyleSheetRenderState.<clinit>(StyleSheetRenderState.java:72)
	at org.loboevolution.html.domimpl.DOMNodeImpl.<clinit>(DOMNodeImpl.java:73)
	at org.loboevolution.html.parser.DocumentBuilderImpl.createDocument(DocumentBuilderImpl.java:194)
	at org.loboevolution.html.test.SimpleHtmlRendererContext.createDocument(SimpleHtmlRendererContext.java:555)
	at org.loboevolution.html.test.SimpleHtmlRendererContext.submitFormSync(SimpleHtmlRendererContext.java:512)
	at org.loboevolution.html.test.SimpleHtmlRendererContext$1.run(SimpleHtmlRendererContext.java:331)
```

```
ERROR ExternalResourcesCache org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: cache)
 org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: cache)
	at org.sqlite.core.DB.newSQLException(DB.java:941)
	at org.sqlite.core.DB.newSQLException(DB.java:953)
	at org.sqlite.core.DB.throwex(DB.java:918)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:47)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
	at org.loboevolution.html.dombl.ExternalResourcesCache.getSourceCache(ExternalResourcesCache.java:58)
	at org.loboevolution.html.style.CSSUtilities.parse(CSSUtilities.java:120)
	at org.loboevolution.html.domimpl.HTMLLinkElementImpl.processLink(HTMLLinkElementImpl.java:180)
	at org.loboevolution.html.domimpl.HTMLLinkElementImpl.setUserData(HTMLLinkElementImpl.java:153)
	at org.loboevolution.html.parser.HtmlParser.parseToken(HtmlParser.java:471)
	at org.loboevolution.html.parser.HtmlParser.parseToken(HtmlParser.java:383)
	at org.loboevolution.html.parser.HtmlParser.parseToken(HtmlParser.java:383)
	at org.loboevolution.html.parser.HtmlParser.parse(HtmlParser.java:248)
	at org.loboevolution.html.parser.HtmlParser.parse(HtmlParser.java:210)
	at org.loboevolution.html.domimpl.HTMLDocumentImpl.load(HTMLDocumentImpl.java:347)
	at org.loboevolution.html.domimpl.HTMLDocumentImpl.load(HTMLDocumentImpl.java:318)
	at org.loboevolution.html.test.SimpleHtmlRendererContext.submitFormSync(SimpleHtmlRendererContext.java:517)
	at org.loboevolution.html.test.SimpleHtmlRendererContext$1.run(SimpleHtmlRendererContext.java:331)
```

Can you help me solve this?

**Comment by Sciss** [comment]
I'm a step further now using `PlatformInit` as entry point. Sql errors have disappeared, new error is this as I try to load URL:

```
[error] ERROR RequestEngine java.lang.IllegalStateException: No clientlets found for response: ClientletResponseImpl[url=https://www.sciss.de,method=GET,mimeType=text/html,fromCache=false,requestType=OPEN_WINDOW].
[error]  java.lang.IllegalStateException: No clientlets found for response: ClientletResponseImpl[url=https://www.sciss.de,method=GET,mimeType=text/html,fromCache=false,requestType=OPEN_WINDOW].
[error] 	at org.loboevolution.context.ClientletFactory.getClientlet(ClientletFactory.java:97)
[error] 	at org.loboevolution.request.ClientletRequestHandler.processResponse(ClientletRequestHandler.java:121)
[error] 	at org.loboevolution.request.RequestEngine.processHandler(RequestEngine.java:963)
[error] 	at org.loboevolution.request.RequestEngine.access$200(RequestEngine.java:85)
[error] 	at org.loboevolution.request.RequestEngine$RequestHandlerTask.lambda$run$0(RequestEngine.java:1139)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at org.loboevolution.request.RequestEngine$RequestHandlerTask.run(RequestEngine.java:1145)
[error] 	at org.loboevolution.util.SimpleThreadPool$ThreadRunnable.run(SimpleThreadPool.java:198)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

Thanks for help!

**Comment by oswetto** [comment]
Hello Sciss,
thanks for testing loboevolution. 

Step0: run build.xml
Step0: Check if ant (sorry i don't know sbt ) have created this path "C://tmp//lobo-build//lobo-0.99.3//ext" folder with external lib and lboo lib(cobra-no-commons, primary.jar)
Step2: In main method of EntryPoint  set "ext.dirs"
System.setProperty("ext.dirs","C://tmp//lobo-build//lobo-0.99.3//ext"); 
Step3: Run main
Step4: Attention loboevolution is in alpha stage more css2 and css3 not work
